[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[build]
target = "x86_64-dev_os.json"

# Use bootimage to run anything (run/test) for this target in QEMU
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
